version: 1.0.{build}
environment:
  NugetApiKey:
    secure: TODO
build_script:
- ps: ./build.ps1 -target Package
artifacts:
- path: ./nuget/*.nupkg
- path: ./output/*
deploy:
- provider: NuGet
  api_key:
    secure: TODO
  on:
    appveyor_repo_tag: true